### ISSUE TITLE
HelmValues component support custom the configuration key.

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/velaux#481]
Currently, the value key only is selected, and the options are generated from `value.yaml`. but some annotated configuration options can not be generated. 

example:
```
metrics:
  # datadog:
  #   address: 127.0.0.1:8125
  # influxdb:
  #   address: localhost:8089
  #   protocol: udp
  prometheus:
    entryPoint: metrics
  #  addRoutersLabels: true
  # statsd:
  #   address: localhost:8125
```
