### ISSUE TITLE
Component parameters are mixed after the component type is changed

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/velaux#505]
**Describe the bug**

When adding a component, the default component type is `webservice`. I switch to `helm` and completed configuring the component parameters. But the final parameters are mixed with the default parameters of the `webservice`.

example:

```
 components:
  - name: istio-gateway
    properties:
      chart: gateway
      repoType: helm
      secretRef: ""
      url: https://istio-release.storage.googleapis.com/charts
      values: {}
      version: 1.13.3
    type: helm
  - name: istio-gateway-base
    properties:
      chart: base
      exposeType: ClusterIP
      repoType: helm
      secretRef: ""
      url: https://istio-release.storage.googleapis.com/charts
      values: {}
      version: 1.13.3
    type: helm
  - name: istio-gateway-istiod
    properties:
      chart: istiod
      exposeType: ClusterIP
      repoType: helm
      secretRef: ""
      url: https://istio-release.storage.googleapis.com/charts
      values: {}
      version: 1.13.3
    type: helm
```

the `exposeType` field does not belong to helm component.
