### ISSUE TITLE
[Feature] Add Pipeline studio page

### ISSUE THREAD

**Issue by barnettZQG** [kubevela/velaux#630]
**Is your feature request related to a problem? Please describe.**

Now, VelaUX support creates and edits Pipeline steps via YAML. This is difficult for the end user.

```yaml
- name: Enable Prism
  type: addon-operation
  properties:
    addonName: vela-prism

- name: Enable o11y
  type: addon-operation
  properties:
    addonName: o11y-definitions
    operation: enable
    args:
      - --override-definitions

- name: Prepare Prometheus
  type: step-group
  subSteps:
    - name: get-exist-prometheus
      type: list-config
      properties:
        template: prometheus-server
        namespace: vela-system
      outputs:
        - name: prometheus
          valueFrom: "output.configs"

    - name: prometheus-server
      inputs:
        - from: prometheus
          parameterKey: configs
      if: context.readConfig == "false" || len(inputs.prometheus) == 0
      type: addon-operation
      properties:
        addonName: prometheus-server
        operation: enable
        args:
          - memory=1024Mi
```

There is a graph page to show the Pipeline run status:

![image](https://user-images.githubusercontent.com/18493394/198927021-33af1d3c-41ae-4c9c-8a90-5fcf7ccd7e72.png)

So, we could add an editing mode for the Pipeline Graph and launch a Pipeline Studio page. Users could add the step and sub-step. The step type options come from the workflow step definitions. The step form built with drawer page and includes:

1. Name, Alias   [Input]
2. Type              [Select]
3. Properties     [UISchema]
4. If                    [Input]
5. Outputs         [Structs]
6. Inputs            [Structs / OutputNameSelect]

##  Process requirements. 

1. We should notify the user if he leaves the studio page without committing the Pipeline.
2. The Pipeline has at least one step.
3. User only could add the step group in the first layer.
