### ISSUE TITLE
[Bug] VelaUX can not show the parameters of Trait Expose

### ISSUE THREAD

**Issue by StevenLeiZhang** [kubevela/velaux#659]
**Describe the bug**

There is one parameter "port" in Trait Expose, but VelaUX can not show it

![image](https://user-images.githubusercontent.com/14890978/211129723-152a8730-9b1d-4bcc-9a25-577784fd0303.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Additional context**

**Comment by barnettZQG** [comment]
@StevenLeiZhang What the parameter type is?

**Comment by StevenLeiZhang** [comment]
> @StevenLeiZhang What the parameter type is?

Expose is build-in Trait .

```
- sort: 101
  label: Port
  description: Specify the exposion ports
  validate:
    required: true
    immutable: false
  jsonKey: port
  uiType: Numbers
```
