### ISSUE TITLE
[Feature] support create TLS certificate in velaux

### ISSUE THREAD

**Issue by wonderflow** [kubevela/velaux#722]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/2173670/227466560-1d4d1a6f-c118-4a7f-bc9f-7bf24e153543.png)

To configure a https gateway, we need to create a configure for TLS certificate and key, it's widely used in Kubernetes like:

```
kubectl create secret tls nginx-tls-secret --cert=tls.crt --key=tls.key -n default
```

It will be used in ingress like:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.oam.dev/name: nginx
    app.oam.dev/namespace: default
  name: nginx
  namespace: default
spec:
  rules:
  - host: nginx.myhost.com
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - nginx.myhost.com
    secretName: nginx-tls-secret
```

In KubeVela, we also uses the secret like below:

![image](https://user-images.githubusercontent.com/2173670/227467380-533c7136-b209-4019-8cba-21df73fbe12e.png)

After we configured in velaux, it should be a dropdown list and can be discovered automatically.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
